FROM docker.io/library/golang:1.24-alpine AS builder
WORKDIR /app

RUN apk add --no-cache protobuf
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.33.0
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

COPY . .

RUN go mod tidy

RUN protoc -I./proto-context --go_out=./ --go-grpc_out=./ ./proto-context/service.proto

RUN go build -o api-gateway ./cmd

FROM docker.io/library/alpine:latest
WORKDIR /app

COPY --from=builder /app/api-gateway ./api-gateway

ENTRYPOINT ["./api-gateway"]
