FROM ghcr.io/ggml-org/whisper.cpp:main-cuda-7849aff7a2e1f4234aa31b01a1870906d5431959 AS builder

WORKDIR /app

COPY entrypoint.sh build-functions.sh ./

RUN ./entrypoint.sh install_deps
RUN ./entrypoint.sh build_libs
RUN ./entrypoint.sh create_configs
RUN ./entrypoint.sh build_grpc

COPY . .

RUN ./entrypoint.sh build_minio
RUN ./entrypoint.sh build_app

FROM ghcr.io/ggml-org/whisper.cpp:main-cuda-7849aff7a2e1f4234aa31b01a1870906d5431959

WORKDIR /app

COPY --from=builder /app/whisper_grpc_server ./whisper_grpc_server

ENTRYPOINT ["./whisper_grpc_server"]
